sa-token:
  token-name: jh-token
  timeout: 604800
  activity-timeout: 259200
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  jwt-secret-key: kjvwy2jkfsdhk

spring:
  profiles:
    active: debug
  data:
    redis:
      database: 0
      timeout: 3000
      password: null
      host: 127.0.0.1
      port: 6379

#wechat:
#  appid: wxc9615a04550bbfdb
#  secret: ef309aba284fc74a6a5228f12d3803e7